meta:
  schema-version: 0.1.0
  created-on: "2024-01-24T12:20:45Z"
  cli-version: 0.2.0
projects:
  eifr-wordle13b8da79-3b05-4313-ab6e-96de9e6695c2:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "7"
    overrides:
      tough-cookie:
        4.0.0:
          use: 4.0.0-sp1
      loader-utils:
        2.0.2:
          use: 2.0.2-sp1
        1.4.0:
          use: 1.4.0-sp1
      decode-uri-component:
        0.2.0:
          use: 0.2.0-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      semver:
        7.3.5:
          use: 7.3.5-sp1
        6.3.0:
          use: 6.3.0-sp1
        7.0.0:
          use: 7.0.0-sp1
      async:
        2.6.3:
          use: 2.6.3-sp1
      nth-check:
        1.0.2:
          use: 1.0.2-sp1
      postcss:
        7.0.39:
          use: 7.0.39-sp1
      word-wrap:
        1.2.3:
          use: 1.2.3-sp1
      json5:
        2.2.0:
          use: 2.2.0-sp1
